### ISSUE TITLE
SSPL License Issues

### ISSUE THREAD

**Issue by fakerybakery** [JJTech0130/pypush#79] opened 2023-12-08 23:52 UTC
Hi,
I noticed on your GitHub profile you mentioned PyPush was open sourced, however according to the creators of the SSPL license (MongoDB), the SSPL license is not open sourced ([source](mongodb.com/licensing/server-side-public-license)).
Are there any plans to perhaps switch the license in the future?
Thank you for creating this incredible project!

**Comment by ezfe** [comment] 2023-12-09 02:43
I am not a contributor or representative of this project, but I wanted to reply to you since I'm a bit confused.

You say that MongoDB (the creators of SSPL) say the license is not open sourced. I'm not sure what you mean by this. They say the license _is_ an open source license.

Other people say it is not, however I have not found any compelling reasons beyond ambiguity/quality concerns in the license. I have been searching for other reasons. If you have any reference to a specific concern and how it might impact this project, I'm sure the author of this project would appreciate it.

**Comment by fakerybakery** [comment] 2023-12-09 02:48
Hi,
Apologies, I could've been clearer. They do not specifically say that it is not an open source license, but they have a section called "Will MongoDB continue to provide open source software?" which implies that the license is not open sourced.
However, the OSI has specifically called the SSPL not open sourced in a [blog post](https://blog.opensource.org/the-sspl-is-not-an-open-source-license/).

> We’ve seen that several companies have abandoned their original dedication to the open source community by switching their core products from an open source license, one approved by the Open Source Initiative, to a “fauxpen” source license. The hallmark of a fauxpen source license is that those who made the switch claim that their product continues to remain “open” under the new license, but the new license actually has taken away user rights.
> 
> The license du jour is the Server Side Public License. This license was submitted to the Open Source Initiative for approval but later [withdrawn by the license steward](http://lists.opensource.org/pipermail/license-review_lists.opensource.org/2019-March/003989.html) when it became clear that the license would not be approved.

[(source)](https://blog.opensource.org/the-sspl-is-not-an-open-source-license/)

**Comment by http403** [comment] 2023-12-09 09:14
https://blog.opensource.org/the-sspl-is-not-an-open-source-license/

SSPL is a "source avaliable" license, not an Open Source license approved by known entities.

The problem is in section 13 of the license as a violation of [OSD6](https://opensource.org/osd/) by OSI. Otherwise, it's a heavily modified version of AGPLv3.

I'm no legal expert so I might read it the wrong way. AFAIUI, section 13 make cloud providers who use this work to provide service over a network to offer the source for free, rather at opportunity, and force other parts of said service, such as UI and monitoring tools, to be release under SSPL. It simply means make the whole service stack sources avaliable to all for free, if I understand correctly.

How does it make it violate OSD6? I have no idea. And again, I'm not a legal expert so do **NOT** count on my words.

**Comment by enoch-dev** [comment] 2023-12-09 09:29
Here's more info on the mongodb license issue

https://www.zdnet.com/article/mongodb-open-source-server-side-public-license-rejected/

**Comment by Zipdox2** [comment] 2023-12-12 20:39
Yeah this is non-free software.

**Comment by fakerybakery** [comment] 2023-12-12 21:20
The OSI provided some more details:

https://blog.opensource.org/the-sspl-is-not-an-open-source-license/

**Comment by JJTech0130** [comment] 2023-12-12 21:22
Yeah, when I licensed this I was not aware that the SSPL does not count as an "Open Source License". Sorry about that, I can't actually do anything about it now. I don't think there are any actual problems with the SSPL license for most people's use of it; it's not like it's polished software that could be deployed in production anyway.

In the long run, Beeper might relicense it, we'll see.

**Comment by fakerybakery** [comment] 2023-12-12 22:05
Thanks for your explanation! Also, do you know if the Beeper Mini outage affects this package?

**Comment by JJTech0130** [comment] 2023-12-12 22:06
That is a separate issue, but the answer is it did.
Basically Apple changed 2 things, one was a super simple change that broke pypush and Beeper entirely, but we fixed pretty quickly, has already landed in the `async` branch.
the other change broke phone number registration, which has not been fixed in Beeper Mini or pypush yet

**Comment by eris-webserv** [comment] 2023-12-12 23:20
What did they do to phone number registration anyway? Do you know the specifics?

**Comment by danipoak** [comment] 2023-12-13 02:04
I'm closing this since it's veering off track. Join the discord if you want to discuss specifics.

**Closed as completed** 2023-12-13 02:04 UTC
