### ISSUE TITLE
Validation data expired

### ISSUE THREAD

**Issue by selenium-can** [JJTech0130/pypush#80] opened 2023-12-09 11:31 UTC
I tried to update data.plist, but I got a raise Exception("Validation data expired! ") Could you please help me solve this headache?
Also, how do I create a batch data.plist, or make it update automatically

**Comment by P5-2005** [comment] 2023-12-09 16:10
> I tried to update data.plist, but I got a raise Exception("Validation data expired! ") Could you please help me solve this headache? Also, how do I create a batch data.plist, or make it update automatically

on real mac or hackintosh you own, use this to get your data.plist extracted:
https://github.com/JJTech0130/nacserver
but for now its down as service, maybe next update will fix the current issue, join the discord server for more update and details

**Comment by selenium-can** [comment] 2023-12-09 16:26
I've joined discord, but I don't have permission to speak.As for "on real mac or hackintosh you own, use this to get your data.plist extracted", I have tried and the error is "Response code: 6004 ", "Validation data expired! Now I don't know how to solve this problem, can you give me another contact information for you? It is convenient for me to communicate with you and thank you.

**Comment by selenium-can** [comment] 2023-12-09 16:26
> > I tried to update data.plist, but I got a raise Exception("Validation data expired! ") Could you please help me solve this headache? Also, how do I create a batch data.plist, or make it update automatically
> 
> on real mac or hackintosh you own, use this to get your data.plist extracted: https://github.com/JJTech0130/nacserver but for now its down as service, maybe next update will fix the current issue, join the discord server for more update and details

As for "on real mac or hackintosh you own, use this to get your data.plist extracted", I have tried and the error is "Response code: 6004 ", "Validation data expired! Now I don't know how to solve this problem, can you give me another contact information for you? It is convenient for me to communicate with you and thank you.

**Comment by Kasherpete** [comment] 2023-12-09 17:37
Pypush is currently down, we're working hard to fix it atm.

**Comment by elminson** [comment] 2023-12-10 19:39
Thank you @Kasherpete , I been running some test on my end. Looks like an issue with the self.queue in apns.py
Let me know if you need any help

**Comment by AngeloD2022** [comment] 2023-12-11 12:41
> Pypush is currently down, we're working hard to fix it atm.

Do we know which specific part(s) have been broken by Apple?

**Comment by SpaceSaver** [comment] 2023-12-11 14:56
> > Pypush is currently down, we're working hard to fix it atm.
> 
> Do we know which specific part(s) have been broken by Apple?

Yes, will be published after Beeper Mini is fixed.

**Comment by vmd1** [comment] 2023-12-11 19:50
So when can we expect that to be as i'm pretty sure beeper mini has resumed services if i'm not mistaken.

**Comment by Cypheriel** [comment] 2023-12-11 22:19
Hello. This issue *should* be fixed in the [latest commit of the async branch](https://github.com/JJTech0130/pypush/commit/8220f3407c96c975d0dd699fd5ab41f56f372c47). If this does not solve the issue, please let us know.

**Comment by elminson** [comment] 2023-12-11 23:09
I can confirm the branch async branch works :), I will do some adjustment for my code :) @Cypheriel thank you so much

**Comment by danipoak** [comment] 2023-12-11 23:39
Closing. Fixed with Async updates.

**Closed as completed by danipoak** 2023-12-11 23:39 UTC

**Comment by selenium-can** [comment] 2023-12-16 07:35
This problem is still unable to send messages, but can be logged in.
















At 2023-12-12 06:19:18, "Mikel" ***@***.***> wrote:

Hello. This issue should be fixed in the latest commit of the async branch. If this does not solve the issue, please let us know.

**Comment by SpaceSaver** [comment] 2023-12-16 14:35
> This problem is still unable to send messages, but can be logged in. At 2023-12-12 06:19:18, "Mikel" ***@***.***> wrote: Hello. This issue should be fixed in the latest commit of the async branch. If this does not solve the issue, please let us know. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

Are you on the async branch?

**Comment by selenium-can** [comment] 2023-12-16 14:40
Yes, I am on async branch and couldn't send messages during today's test and did not enable hread.Message ID



At 2023-12-16 22:36:09, "SpaceSaver" ***@***.***> wrote:

This problem is still unable to send messages, but can be logged in. At 2023-12-12 06:19:18, "Mikel" @.> wrote: Hello. This issue should be fixed in the latest commit of the async branch. If this does not solve the issue, please let us know. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.>

Are you on the async branch?

**Comment by SpaceSaver** [comment] 2023-12-16 14:43
> Yes, I am on async branch and couldn't send messages during today's test and did not enable hread.Message ID At 2023-12-16 22:36:09, "SpaceSaver" ***@***.***> wrote: This problem is still unable to send messages, but can be logged in. At 2023-12-12 06:19:18, "Mikel" @.> wrote: Hello. This issue should be fixed in the latest commit of the async branch. If this does not solve the issue, please let us know. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.> Are you on the async branch? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

Apple appears to have blocked us again.

**Comment by selenium-can** [comment] 2023-12-16 14:48
Oh my God, how can I solve this problem, can you help me solve, how often Apple blocks us?



At 2023-12-16 22:44:10, "SpaceSaver" ***@***.***> wrote:

Yes, I am on async branch and couldn't send messages during today's test and did not enable hread.Message ID At 2023-12-16 22:36:09, "SpaceSaver" @.> wrote: This problem is still unable to send messages, but can be logged in. At 2023-12-12 06:19:18, "Mikel" @.> wrote: Hello. This issue should be fixed in the latest commit of the async branch. If this does not solve the issue, please let us know. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.> Are you on the async branch? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.>

Apple appears to have blocked us again.

**Comment by SpaceSaver** [comment] 2023-12-16 14:49
> Oh my God, how can I solve this problem, can you help me solve, how often Apple blocks us? At 2023-12-16 22:44:10, "SpaceSaver" ***@***.***> wrote: Yes, I am on async branch and couldn't send messages during today's test and did not enable hread.Message ID At 2023-12-16 22:36:09, "SpaceSaver" @.> wrote: This problem is still unable to send messages, but can be logged in. At 2023-12-12 06:19:18, "Mikel" @.> wrote: Hello. This issue should be fixed in the latest commit of the async branch. If this does not solve the issue, please let us know. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.> Are you on the async branch? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.> Apple appears to have blocked us again. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

Whenever they feel like it.  Which is becoming weekly.

**Comment by selenium-can** [comment] 2023-12-16 15:05
Ha ha, it seems that this is a sad story. How can I learn to solve this problem as easily as you do?



At 2023-12-16 22:50:02, "SpaceSaver" ***@***.***> wrote:

Oh my God, how can I solve this problem, can you help me solve, how often Apple blocks us? At 2023-12-16 22:44:10, "SpaceSaver" @.> wrote: Yes, I am on async branch and couldn't send messages during today's test and did not enable hread.Message ID At 2023-12-16 22:36:09, "SpaceSaver" @.> wrote: This problem is still unable to send messages, but can be logged in. At 2023-12-12 06:19:18, "Mikel" @.> wrote: Hello. This issue should be fixed in the latest commit of the async branch. If this does not solve the issue, please let us know. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.> Are you on the async branch? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.> Apple appears to have blocked us again. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.>

Whenever they feel like it. Which is becoming weekly.

**Comment by SpaceSaver** [comment] 2023-12-16 15:09
What do you plan on using the project for?

**Comment by selenium-can** [comment] 2023-12-16 15:15
I plan to send regular greetings to my friends and regular tasks to myself. And chatgpt can help me reply automatically when my friends reply to my messages. For me, this is a challenging and meaningful thing.



At 2023-12-16 23:09:55, "SpaceSaver" ***@***.***> wrote:

What do you plan on using the project for?
